export default [
  {
    customer: "Matthew Taylor",
    jobNumber: 10448,
    category: "Inspection Point",
    inspector: "Troy Simon",
    date: "19-46-2023",
    time: "11:49 AM",
    siteAddress: "3198 Donec Av.",
    status: "Completed",
    description:
      "dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non",
    id: 1,
  },
  {
    customer: "Vladimir Dunlap",
    jobNumber: 1949,
    category: "Maintenance Inspection",
    inspector: "Eaton Malone",
    date: "04-55-2023",
    time: "04:40 PM",
    siteAddress: "Ap #607-2124 Non, Rd.",
    status: "InProgress",
    description:
      "Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero.",
    id: 2,
  },
  {
    customer: "Arthur England",
    jobNumber: 84911,
    category: "Pre-Plaster Inspection",
    inspector: "Samuel Wolfe",
    date: "04-47-2022",
    time: "08:40 PM",
    siteAddress: "P.O. Box 630, 3361 Eget Road",
    status: "InProgress",
    description:
      "dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras",
    id: 3,
  },
  {
    customer: "Dane Spears",
    jobNumber: 1612,
    category: "Inspection Maintenance",
    inspector: "Berk Wolfe",
    date: "12-55-2024",
    time: "05:14 PM",
    siteAddress: "Ap #877-2014 Mauris St.",
    status: "Completed",
    description:
      "eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus",
    id: 4,
  },
  {
    customer: "Gail Boyer",
    jobNumber: 43204,
    category: "Inspection Lock-up",
    inspector: "Colt Simpson",
    date: "07-38-2022",
    time: "01:20 PM",
    siteAddress: "849-848 Arcu. St.",
    status: "InProgress",
    description:
      "mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis",
    id: 5,
  },
  {
    customer: "Jolie Williamson",
    jobNumber: 67001,
    category: "Frame Inspection",
    inspector: "Katell Hale",
    date: "29-25-2023",
    time: "01:11 PM",
    siteAddress: "474-944 Mauris. St.",
    status: "Completed",
    description:
      "libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat.",
    id: 6,
  },
  {
    customer: "Salvador Miles",
    jobNumber: 34479,
    category: "Time Inspection",
    inspector: "Aretha Compton",
    date: "02-06-2024",
    time: "02:11 PM",
    siteAddress: "304-5852 Phasellus St.",
    status: "InProgress",
    description:
      "enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat",
    id: 7,
  },
  {
    customer: "Gray Morgan",
    jobNumber: 90475,
    category: "Fixing Inspection",
    inspector: "Priscilla Lloyd",
    date: "14-47-2024",
    time: "04:41 AM",
    siteAddress: "196-2174 Curabitur Avenue",
    status: "Completed",
    description:
      "Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy",
    id: 8,
  },
  {
    customer: "Jemima Potter",
    jobNumber: 6279,
    category: "Waterproofing Inspection",
    inspector: "Carly Bowen",
    date: "22-55-2023",
    time: "10:45 AM",
    siteAddress: "804-6695 Lorem Avenue",
    status: "Completed",
    description:
      "sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu.",
    id: 9,
  },
  {
    customer: "Felicia House",
    jobNumber: 60470,
    category: "Waterproofing Inspection",
    inspector: "Vernon Roberson",
    date: "08-17-2024",
    time: "07:30 PM",
    siteAddress: "6472 Nibh Rd.",
    status: "Pending",
    description:
      "in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui",
    id: 10,
  },
  {
    customer: "Daria Harris",
    jobNumber: 37916,
    category: "Handover Inspection",
    inspector: "Upton Mcleod",
    date: "18-19-2023",
    time: "11:23 PM",
    siteAddress: "Ap #807-2851 Sed Street",
    status: "Pending",
    description:
      "Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales",
    id: 11,
  },
  {
    customer: "Hedley Mayo",
    jobNumber: 46783,
    category: "Pre-Slab Inspection",
    inspector: "Ashely Castaneda",
    date: "23-06-2024",
    time: "08:47 PM",
    siteAddress: "4769 Semper Rd.",
    status: "Completed",
    description:
      "Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae Phasellus",
    id: 12,
  },
  {
    customer: "Justine Mills",
    jobNumber: 47104,
    category: "In Time",
    inspector: "Yardley Macdonald",
    date: "16-05-2024",
    time: "01:50 PM",
    siteAddress: "2378 Semper Avenue",
    status: "InProgress",
    description:
      "Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut,",
    id: 13,
  },
  {
    customer: "Jolene Horton",
    jobNumber: 15796,
    category: "Handover Inspection",
    inspector: "Herman Perez",
    date: "09-18-2024",
    time: "06:20 AM",
    siteAddress: "887-3295 Lacus. Rd.",
    status: "Completed",
    description:
      "interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla.",
    id: 14,
  },
  {
    customer: "Keelie Powers",
    jobNumber: 10459,
    category: "Inspection Point",
    inspector: "Felix Brady",
    date: "18-47-2024",
    time: "12:26 AM",
    siteAddress: "3464 Erat Rd.",
    status: "InProgress",
    description:
      "elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas",
    id: 15,
  },
  {
    customer: "Harding Jarvis",
    jobNumber: 99236,
    category: "Maintenance Inspection",
    inspector: "Britanni Lott",
    date: "10-05-2023",
    time: "01:27 AM",
    siteAddress: "797-9376 Duis St.",
    status: "InProgress",
    description:
      "Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer",
    id: 16,
  },
  {
    customer: "Stone Flynn",
    jobNumber: 45075,
    category: "Inspection Lock-up",
    inspector: "Zephania Mccoy",
    date: "24-42-2024",
    time: "09:35 AM",
    siteAddress: "352-4575 At Rd.",
    status: "Completed",
    description:
      "tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu",
    id: 17,
  },
  {
    customer: "Amela Mcguire",
    jobNumber: 37146,
    category: "Inspection Maintenance",
    inspector: "Rhea Church",
    date: "09-24-2023",
    time: "05:37 PM",
    siteAddress: "532-4409 Mi Avenue",
    status: "Completed",
    description:
      "Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales",
    id: 18,
  },
  {
    customer: "Wyoming Sargent",
    jobNumber: 7160,
    category: "Inspection Frame",
    inspector: "Bryar Reid",
    date: "21-37-2023",
    time: "06:00 PM",
    siteAddress: "838-8126 Vitae, Avenue",
    status: "Pending",
    description:
      "felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet,",
    id: 19,
  },
  {
    customer: "Bruno Kennedy",
    jobNumber: 88514,
    category: "Pre-Plaster Inspection",
    inspector: "Wang Nieves",
    date: "19-21-2024",
    time: "03:30 PM",
    siteAddress: "P.O. Box 380, 4176 Pellentesque Av.",
    status: "Completed",
    description:
      "nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at,",
    id: 20,
  },
];
